#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void slowTurnRight(){
	setMotorSpeed(leftMotor, -5);
	setMotorSpeed(rightMotor, 5);
}
void slowTurnLeft(){
	setMotorSpeed(leftMotor, 5);
	setMotorSpeed(rightMotor, -5);
}
void fastForward(){
	setMotorSpeed(leftMotor, 60);
	setMotorSpeed(rightMotor, 60);
}
void goForward(){
	setMotorSpeed(leftMotor, 25);
	setMotorSpeed(rightMotor, 25);
}
void goBackwards(){
	setMotorSpeed(leftMotor, -20);
	setMotorSpeed(rightMotor, -20);
	playSound(soundBeepBeep);

}
void turnLeft(){
	setMotorSpeed(leftMotor, 10);
	setMotorSpeed(rightMotor, -10);
}
void turnRight(){
	setMotorSpeed(leftMotor, -10);
	setMotorSpeed(rightMotor, 10);
}
void touchSensing() {
	while(SensorValue(touchSensor) == 0){
		fastForward();
	}
}

void swingLeft(){
	setMotorSpeed(leftMotor, 22);
	setMotorSpeed(rightMotor, 5);
}
void swingRight(){
	setMotorSpeed(leftMotor, 5);
	setMotorSpeed(rightMotor, 22);
}

task main()
{
	//----------Up
	touchSensing(); // continue till wall detected with touch sensor

	goBackwards();
	sleep(2000);
	turnLeft();
	sleep(1800);
	goForward();
	sleep(2000);
	//--------------line sensing ------

	while(SensorValue(touchSensor) == 0){
		while(SensorValue(colorSensor) == 5 && SensorValue(colorSensor) != 1){
			swingRight();
		}
		while(SensorValue(colorSensor) != 5 && SensorValue(colorSensor) != 1){
			swingLeft();
		}
	}

	//---------------- reverse----------------
	playSound(soundException);
	turnLeft();
	sleep(1700);
	goBackwards();
	sleep(3000);
	while(SensorValue(touchSensor) == 0){
	fastForward();
	}
	goBackwards();
	sleep(200);
	turnLeft();
	sleep(1800);
	while(SensorValue(touchSensor) == 0){
	fastForward();
	}
	turnLeft();
	sleep(1800);
	goForward();
	sleep(2000);



}



/*void wallDetection(){
while(SensorValue(sonarSensor) > 5){
motor[motorA] = 10;
motor[motorB] = 10;
}
motor[motorA] = -10;
motor[motorB] = -10;
wait1Msec(1000);
}*/
