#pragma config(Sensor, S1,     touchSensor,    sensorNone)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorNone)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	resetGyro(S2);
	float kp = 14; // Constant for proportional controllor
	float ki = 2;
	float kd = 1;
	float offset = 0;
	float tp = 0;
	float integral = 0;
	float lasterror = 0;
	float derivative = 0;
	int timer = 0;
	while(timer<100000){



		float gyrovalue = getGyroDegrees(S2);
		float error = gyrovalue - offset;
		integral = integral + error;
		derivative = error - lasterror;
		float Tilt = kp * error + ki*integral + kd*derivative;
		float powerA = tp + Tilt;
		setMotorSpeed(motorA,powerA);
		setMotorSpeed(motorC,powerA);
		lasterror = error;
		timer++;
	}


}
